steps:
- name: test-ruby
  image: getterminus/ruby-ci-image:2.6-je-20190205
  group: bundler
  volumes:
    - name: bundledir
      path: /usr/local/bundle
  commands:
    - bundle check --path=/usr/local/bundle || bundle --local --path=/usr/local/bundle
    - bundle exec rspec