kind: pipeline
name: default

steps:
- name: test-ruby-2.6
  image: getterminus/ruby-docker-images:2.7-je-20200826
  group: test-2.6
  volumes:
    - name: bundledir
      path: /usr/local/bundle
  commands:
    - bundle check --path=/usr/local/bundle || bundle --local --path=/usr/local/bundle
    - bundle exec rspec

- name: test-ruby-2.7
  image: getterminus/ruby-docker-images:2.7-je-20200826
  group: test-2.7
  volumes:
    - name: bundledir
      path: /usr/local/bundle
  commands:
    - bundle check --path=/usr/local/bundle || bundle --local --path=/usr/local/bundle
    - bundle exec rspec

