inherit_from: https://raw.githubusercontent.com/GetTerminus/ruby_shared_configs/master/.rubocop.yml


AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - Makefile
    - vendor/**/*
    - bin/*
    - Guardfile
    - lib/instrument_all_the_things/thread.rb

Naming/AccessorMethodName:
  Exclude:
    - app/controllers/**/*

Layout/EndOfLine:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/Debugger:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Layout/LineLength:
  Enabled: true
  Max: 280
  IgnoreCopDirectives: true
  IgnoredPatterns: ['\A#', '\A\s*sig { .* }\Z']
  Exclude:
    - '**/*_pb.rb'

Metrics/AbcSize:
  Enabled: true
  Max: 46

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/MethodLength:
  Enabled: true
  Max: 32

Layout/ParameterAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Naming/MethodParameterName:
  Enabled: true
  AllowedNames: ['io', 'id', 'to', 'by', 'on', 'in', 'at', '_'] # Defaults + _

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Style/ParallelAssignment:
  Enabled: true

Metrics/ClassLength:
  Max: 240

Metrics/BlockLength:
  Max: 30
  Exclude:
    - spec/**/*.rb
    - '**/*_pb.rb'

Style/BlockDelimiters:
  Enabled: true
  BracesRequiredMethods: ['expect']

Metrics/ParameterLists:
  Max: 6

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*.rb
